# spudtr requires a current GIT_TOKEN on TravisCI kutaslab/spudtr
env:
    - PACKAGE_NAME: spudtr   # for the conda_upload.sh deploy script
language: minimal
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
install:
    - conda install -q conda-build conda-verify
    - conda build conda -c defaults -c conda-forge
    - conda create --name spudtr_env spudtr -c local -c defaults -c conda-forge
    - conda activate spudtr_env  # so tests run in env as installed by conda
    - conda install black pytest-cov
    - conda list
    - lscpu
    - python -c 'import numpy; numpy.show_config()'
script:
    - black --check --verbose --line-length=79 .
    - pytest --cov=spudtr
after_success:
    - pip install codecov && codecov
before_deploy:
    - pip install sphinx sphinx_rtd_theme jupyter nbsphinx nbconvert!=5.4
    - conda install -c conda-forge pandoc
    - conda install anaconda-client
    - conda list
    - sphinx-apidoc -e -f -o docs/source . ./tests/* ./setup.py
    - make -C docs html
    - touch docs/build/html/.nojekyll
deploy:
    # upload github vN.N.N releases to Anaconda Cloud with TravisCI
    - provider: script
      skip_cleanup: true
      script: bash ./scripts/conda_upload.sh
      on:
          all_branches: true

    # only master branch refreshes the docs
    - provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      on:
          branch: master
      target_branch: gh-pages  # that's the default anyway, just to be explicit
      local_dir: docs/build/html

